import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { ArrowRight, Database, Sparkles } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";
import { useAuth } from "@/lib/auth-store";
import { LandingHeroDemo } from "@/components/landing-hero-demo";
import { AnimatedBackdrop } from "@/components/animated-backdrop";
import { LandingHowItWorks } from "@/components/landing-how-it-works";
import { LandingStats } from "@/components/landing-stats";
import { LandingMarquee } from "@/components/landing-marquee";
import { LandingShowcase } from "@/components/landing-showcase";
import { LandingFeatureCards } from "@/components/landing-feature-cards";
import { ScrollReveal } from "@/components/scroll-reveal";
export default function LandingPage() {
    const accessToken = useAuth((s) => s.accessToken);
    const isAuthed = !!accessToken;
    return (_jsxs("div", { className: "relative min-h-screen bg-background text-foreground overflow-x-hidden", children: [_jsx(AnimatedBackdrop, {}), _jsxs("header", { className: "h-14 flex items-center justify-between px-6 border-b border-border bg-card/50 backdrop-blur-sm sticky top-0 z-20", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 font-semibold", children: [_jsx(Database, { className: "h-5 w-5 text-primary" }), "DB Studio"] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(ThemeToggle, {}), isAuthed ? (_jsxs(Link, { to: "/connections", className: "text-sm bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-3 py-1.5 inline-flex items-center gap-1.5", children: ["Open app ", _jsx(ArrowRight, { className: "h-3.5 w-3.5" })] })) : (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "text-sm text-muted-foreground hover:text-foreground px-3 py-1.5", children: "Sign in" }), _jsx(Link, { to: "/signup", className: "text-sm bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-3 py-1.5", children: "Sign up" })] }))] })] }), _jsxs("section", { className: "relative overflow-hidden", children: [_jsx("div", { "aria-hidden": true, className: "absolute inset-0 -z-10", style: {
                            background: "radial-gradient(ellipse 70% 40% at 20% 20%, rgba(62,207,142,0.15), transparent 60%), radial-gradient(ellipse 60% 50% at 90% 80%, rgba(62,207,142,0.08), transparent 60%)",
                        } }), _jsxs("div", { className: "max-w-6xl mx-auto px-6 py-16 sm:py-24 grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)] gap-12 items-center", children: [_jsxs("div", { children: [_jsxs("div", { className: "inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs text-muted-foreground mb-6", children: [_jsx(Sparkles, { className: "h-3 w-3" }), "Every tool a DB admin actually needs, in one place"] }), _jsxs("h1", { className: "text-4xl sm:text-5xl font-semibold tracking-tight", children: ["The database studio for teams who", " ", _jsx("span", { className: "text-primary", children: "don't want five tools" }), "."] }), _jsx("p", { className: "mt-6 text-base sm:text-lg text-muted-foreground max-w-xl", children: "Browse, query, schedule, back up, and share work across Postgres, MySQL, SQL Server, and SQLite. One interface, role-aware, with an AI that actually knows your schema." }), _jsx("div", { className: "mt-8 flex items-center gap-3 flex-wrap", children: isAuthed ? (_jsxs(Link, { to: "/connections", className: "inline-flex items-center gap-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-5 py-2.5 text-sm font-medium", children: ["Go to your connections ", _jsx(ArrowRight, { className: "h-4 w-4" })] })) : (_jsxs(_Fragment, { children: [_jsxs(Link, { to: "/signup", className: "inline-flex items-center gap-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-5 py-2.5 text-sm font-medium", children: ["Get started free ", _jsx(ArrowRight, { className: "h-4 w-4" })] }), _jsx(Link, { to: "/login", className: "inline-flex items-center gap-2 border border-border hover:bg-accent rounded-md px-5 py-2.5 text-sm", children: "Sign in" })] })) }), _jsxs("div", { className: "mt-6 flex items-center gap-4 text-[11px] text-muted-foreground", children: [_jsxs("span", { className: "inline-flex items-center gap-1.5", children: [_jsx("span", { className: "h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" }), "Live demo \u2192"] }), _jsx("span", { children: "Postgres \u00B7 MySQL \u00B7 SQL Server \u00B7 SQLite" })] })] }), _jsx("div", { className: "landing-hero-respect-rm", children: _jsx(LandingHeroDemo, {}) })] })] }), _jsx(LandingStats, {}), _jsx(LandingMarquee, {}), _jsx(LandingHowItWorks, {}), _jsx(LandingShowcase, {}), _jsx(LandingFeatureCards, {}), _jsx("section", { className: "landing-animations max-w-5xl mx-auto px-6 py-24", children: _jsx(ScrollReveal, { from: "up", children: _jsxs("div", { className: "relative rounded-2xl border border-border bg-linear-to-br from-primary/15 via-card to-card p-8 sm:p-14 text-center overflow-hidden", children: [_jsx("div", { "aria-hidden": true, className: "absolute inset-0 opacity-[0.12] pointer-events-none", style: {
                                    backgroundImage: "radial-gradient(rgba(62,207,142,0.6) 1px, transparent 1px)",
                                    backgroundSize: "24px 24px",
                                } }), _jsxs("h2", { className: "relative text-3xl sm:text-4xl font-semibold tracking-tight", children: ["Open source. Self-hostable. ", _jsx("span", { className: "text-primary", children: "Yours." })] }), _jsx("p", { className: "relative mt-4 text-muted-foreground max-w-xl mx-auto", children: "Run it in your infra, point it at your databases, give your team access. Connection credentials are encrypted with AES-256-GCM and never leave your server." }), _jsx("div", { className: "relative mt-8 flex items-center justify-center gap-3 flex-wrap", children: _jsxs(Link, { to: isAuthed ? "/connections" : "/signup", className: "inline-flex items-center gap-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-6 py-3 text-sm font-medium shadow-lg shadow-primary/20", children: [isAuthed ? "Open the app" : "Start using it", " ", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] }) }) }), _jsxs("footer", { className: "border-t border-border text-xs text-muted-foreground py-6 text-center", children: ["\u00A9 ", new Date().getFullYear(), " DB Studio"] })] }));
}
