import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from "react-router-dom";
import { ArrowLeft, Database, Home } from "lucide-react";
import { useAuth } from "@/lib/auth-store";
export default function NotFoundPage() {
    const loc = useLocation();
    const accessToken = useAuth((s) => s.accessToken);
    return (_jsxs("div", { className: "min-h-screen bg-background text-foreground flex flex-col", children: [_jsx("header", { className: "h-14 flex items-center px-6 border-b border-border bg-card/50", children: _jsxs(Link, { to: "/", className: "flex items-center gap-2 font-semibold", children: [_jsx(Database, { className: "h-5 w-5 text-primary" }), "DB Studio"] }) }), _jsx("main", { className: "flex-1 flex items-center justify-center px-6 py-12", children: _jsxs("div", { className: "max-w-md w-full text-center space-y-6", children: [_jsx("div", { className: "text-7xl font-bold text-primary/30 tracking-tight", children: "404" }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Page not found" }), _jsxs("p", { className: "mt-2 text-sm text-muted-foreground", children: ["We couldn't find anything at", " ", _jsx("code", { className: "rounded bg-muted px-1.5 py-0.5 font-mono text-xs", children: loc.pathname }), ". It may have been moved, renamed, or never existed."] })] }), _jsxs("div", { className: "flex items-center justify-center gap-2 flex-wrap pt-2", children: [_jsxs("button", { type: "button", onClick: () => window.history.back(), className: "inline-flex items-center gap-1.5 border border-border hover:bg-accent rounded-md px-4 py-2 text-sm", children: [_jsx(ArrowLeft, { className: "h-4 w-4" }), " Go back"] }), _jsxs(Link, { to: accessToken ? "/connections" : "/", className: "inline-flex items-center gap-1.5 bg-primary text-primary-foreground hover:bg-primary/90 rounded-md px-4 py-2 text-sm font-medium", children: [_jsx(Home, { className: "h-4 w-4" }), accessToken ? "Your connections" : "Home"] })] })] }) })] }));
}
