import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "@/lib/utils";
export const Card = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn("rounded-lg border border-border bg-card text-card-foreground shadow-sm", className), ...props })));
Card.displayName = "Card";
export const CardHeader = ({ className, ...props }) => (_jsx("div", { className: cn("flex flex-col space-y-1.5 p-6", className), ...props }));
export const CardTitle = ({ className, ...props }) => (_jsx("h3", { className: cn("font-semibold leading-none tracking-tight", className), ...props }));
export const CardDescription = ({ className, ...props }) => (_jsx("p", { className: cn("text-sm text-muted-foreground", className), ...props }));
export const CardContent = ({ className, ...props }) => (_jsx("div", { className: cn("p-6 pt-0", className), ...props }));
export const CardFooter = ({ className, ...props }) => (_jsx("div", { className: cn("flex items-center p-6 pt-0", className), ...props }));
